
<?php if ($hotels->count() > 0): ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>ホテル名</th>
            <th>部屋タイプ</th>
            <th>宿泊日</th>
            <th>料金</th>
            <th>空室</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Hotels quantity: <?php echo $hotels->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($hotels as $hotel) : ?>
            <tr>
                <td><?php echo $hotel->hotelName; ?></td>
                <td><?php echo $hotel->room_type; ?></td>
                <td><?php echo $hotel->date; ?></td>
                <td><?php echo $hotel->price; ?>円</td>
                <td><?php echo $hotel->stock; ?>室</td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

