<div class="text-center border m-5 p-3">
    <h1>新規会員登録</h1>
    
    <?= $this->tag->form("signup/check") ?>
    <dl>
        <dt>氏名</dt>
        <dd>
            <?= $this->tag->textField("name") ?>
        </dd>
        
        <dt>生年月日</dt>
        <dd>
        <?= $this->tag->dateField(array('birthday', 'value' =>'2000-01-01', 'min' => '1950-01-01')) ?>
        </dd>
    
        <dt>性別</dt>
        <dd>
            <?php $options = array('0' => '----','1' => '男性', '2' => '女性') ?>
            <?= $this->tag->selectStatic(array('gender', $options)) ?>
        </dd>
        
        <dt>メールアドレス</dt>
        <dd>
            <?= $this->tag->emailField("email") ?>
        </dd>
        
        <dt>電話番号</dt>
        <dd>
            <?= $this->tag->numericField("tel") ?>
        </dd>
        
        <dt>パスワード</dt>
        <dd>
            <?= $this->tag->passwordField("password") ?>
        </dd>
    </dl>
    <?= $this->tag->submitButton("確認ページへ") ?>
    <input type="button" onclick="history.back()" value="戻る">
    </form>
</div>
