<div class="text-center border m-5 p-3">
    <h2><?= $hotelName ?></h2>
    <div class="text-center mb-5">
        <img src="images/<?= $hotelImages ?>" width="480px" height="360px">
    </div>
    <?php foreach($rooms as $room): ?>
    <div class="mb-5">
        <div class="border pt-3 text-center m-auto w-75">
            <h3><?= $room->room_type ?></h3>
            <div class="text-left ml-3">
                <p class="text-primary">最大収容人数：<?= $room->capacity ?>名</p>
                <p><?= $inCharge ?>までキャンセル無料</p>
            </div>
            <div class="text-right mr-3">
                <h4>合計：<span style="color: #ff0000;">¥<?= number_format($room->price) ?></span></h4>
                <p>(1部屋/1泊/<?= $personCount ?>名)</p>
            </div>
            <?= $this->tag->form(["detail/confirm", "method" => "get"]) ?>
            <input type="hidden" name="roomId" value="<?= $room->roomId ?>">
            <input type="hidden" name="hotelId" value="<?= $this->request->get('hotelId') ?>">
            <input type="hidden" name="checkInDate" value="<?= $this->request->get('checkInDate') ?>">
            <input type="hidden" name="personCount" value="<?= $this->request->get('personCount') ?>">
            <input type="hidden" name="stayCount" value="<?= $this->request->get('stayCount') ?>">
            <button type="submit" class="btn btn-primary m-3 w-50">予約する</button>
            </form>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<div class="text-center">
<input type="button" onclick="history.back()" value="戻る">
</div>