<div class="text-left">
    <?php if(isset($_SESSION['id'])): ?>
        <p><?= $_SESSION['name']; ?>さん、ようこそ</p> 
    <?php endif; ?>
</div>

<div class="text-right mr-3">
            <?php
            if(isset($_SESSION['id'])){
                echo $this->tag->linkTo(["logout", "ログアウト", 'class' => 'btn btn-primary']); 
            } else{
                echo $this->tag->linkTo(["signup", "新規登録", 'class' => 'btn btn-primary mr-1']);
                echo $this->tag->linkTo(["login", "ログイン", 'class' => 'btn btn-primary']); 
            }
            ?>
</div>
<div class="text-center">
<h2>ホテル検索</h2>
    <div class="border pt-3 pl-3 pr-3 m-auto w-25">
        <?= $this->tag->form(["search", "method" => "get"]); ?>
            <div class="form-group">
                <label>都道府県</label>
                <select name="prefectureId" class="form-control">
                <?php foreach ($prefectures as $prefecture) : ?>
                        <option value="<?= $prefecture->prefectureId ?>"><?= $prefecture->prefectureName ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

                <div class="form-group">
                    <label>チェックイン</label>
                    <?php echo $this->tag->dateField(array('checkInDate', 'class' =>'form-control')); ?>
                    <!-- <input type="date" class="form-control" name="checkInDate"> -->
                    <!-- <input type="date" class="form-control" name="checkInDate" min="<?= date('Y-m-d', strtotime('+3 day')); ?>"> -->
                </div>
                
                <div class="form-group">
                    <label>泊数</label>
                    <?php $options = array('1' => '1泊'); ?>
                    <?php echo $this->tag->selectStatic(array('stayCount', $options, 'class' =>'form-control')); ?>
                    </select>
                </div>
            
            <!-- <div class="form-group">
                <label>泊数</label>
                <select name="stayCount" class="form-control">
                    <?php makeOptions(1, 5, '泊') ?>
                </select>
            </div> -->
            
                <div class="form-group mb-3">
                    <label>人数</label>
                    <select class="form-control" name="personCount">
                        <?php makeOptions(1, 6, '名') ?>
                    </select>
                </div>
                
                <div class="text-center mb-2">
                    <button type="submit" class="btn btn-primary btn-sm">検索する</button>
                </div>
                </form>
    </div>
</div>
    