<div class="text-center border m-auto p-3 w-50">
    <div class="mb-3">
        <h1>お客様情報入力</h1>
    </div>
    
    <?php echo $this->tag->form("form/confirm"); ?>
        <dl>
            <dd>
            <label>氏名</label>
                <?= $this->tag->textField(array('name', 'value' => $_SESSION['name'])) ?>
            </dd>
            
            <dd>
            <label>生年月日</label>
                <?= $this->tag->dateField(array('birthday', 'value' => $birthday)) ?>
            </dd>
        
            <dd>
            <label>性別</label>
                <?php $options = array('1' => '男性', '2' => '女性') ?>
                <?= $this->tag->selectStatic(array('gender', $options)) ?>
                
            </dd>
            
            <dd>
            <label>メールアドレス</label>
                <?= $this->tag->emailField(array('email', 'value' => $email)) ?>
            </dd>
            
            <dd>
            <label>電話番号</label>
                <?= $this->tag->telField(array('tel', 'value' => $tel)) ?>
            </dd>
        </dl>
        <button type="submit" class="btn btn-primary mt-1">予約内容の確認に進む</button>
    </form>
</div>
<div class="text-center">
<input type="button" onclick="history.back()" value="戻る">
</div>
