<div class="text-center border m-auto p-3 w-50">
    <div class="mb-3">
        <h1>お客様情報入力</h1>
    </div>
    
    <?php echo $this->tag->form("form/confirm"); ?>
    <input type="hidden" name="hotelId" value="<?= $hotelId ?>">
    <input type="hidden" name="roomId" value="<?= $roomId ?>">
    <input type="hidden" name="checkInDate" value="<?= $checkInDate ?>">
    <input type="hidden" name="stayCount" value="<?= $stayCount ?>">
    <input type="hidden" name="personCount" value="<?= $personCount ?>">
    <input type="hidden" name="price" value="<?= $price ?>">
        <dl>
            <dd>
            <label>氏名</label>
                <?php echo $this->tag->textField(array('name', 'value' => $_SESSION['name'])); ?>
            </dd>
            
            <dd>
            <label>生年月日</label>
                <?php echo $this->tag->dateField(array('birthday', 'value' => $_SESSION['birthday'])); ?>
            </dd>
        
            <dd>
            <label>性別</label>
                <?php $options = array('1' => '男性', '2' => '女性'); ?>
                <?php echo $this->tag->selectStatic(array('gender', $options)); ?>
                
            </dd>
            
            <dd>
            <label>メールアドレス</label>
                <?php echo $this->tag->emailField(array('email', 'value' => $_SESSION['email'])); ?>
            </dd>
            
            <dd>
            <label>電話番号</label>
                <?php echo $this->tag->telField(array('tel', 'value' => $_SESSION['tel'])); ?>
            </dd>
        </dl>
        <button type="submit" class="btn btn-primary mt-1">予約内容の確認に進む</button>
    </form>
</div>
<div class="text-center">
<input type="button" onclick="history.back()" value="戻る">
</div>
