<div class="text-center border m-5 p-3">
    <h1>ログイン</h1>
    
    <?= $this->tag->form("login/check") ?>
    
    <p>
        <label for="email">メールアドレス</label>
        <?= $this->tag->emailField("email") ?>
    </p>
    
    <p>
        <label for="password">パスワード</label>
        <?= $this->tag->passwordField("password") ?>
    </p>
    
    <p>
        <?= $this->tag->submitButton("ログイン") ?>
    </p>
</form>
</div>
