<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>ホテル予約サイト</title>
    <meta name="description">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
<header class="bg-primary pt-3 pb-3 mb-3">
		<h1 class="ml-5"><a href="../index" class="text-light">ホテル予約サイト</a></h1>
    </header>

<div class="container">

    <?= $this->getContent() ?>
</div>

<footer class="bg-primary p-5 mt-5 mb-2">

</footer>
<script type="text/javascript" src="js/hotel.js"></script>
</body>
</html>