	<?php if(isset($messages)): ?>
	<!-- <?php foreach($messages as $message): ?> -->
  <!-- <p class="mb-3"><?= $message ?></p> -->
  <!-- <?php endforeach; ?> -->
	<?php endif; ?>
<?php if(isset($errors)): ?>
	<div class="text-center">
		<h2 style="color: #ff0000">入力エラー</h2>
		<p><?= $errors ?></p>
		<input type="button" onclick="history.back()" value="戻る">
	</div>
<?php else: ?>

<div class="text-center border m-5 p-3">
    <h1>登録情報確認</h1>
    
    <?= $this->tag->form("customer/completeSignUp") ?>
      <table class="table m-auto w-50">
				<tbody>
					<tr>
						<th scope="row">氏名</th>
						<td><?= htmlspecialchars($name, ENT_QUOTES, 'UTF-8') ?></td>
					</tr>
					<tr>
						<th scope="row">生年月日</th>
						<td><?= date('Y年m月d日', strtotime($birthday)) ?></td>
					</tr>
					<tr>
						<th scope="row">性別</th>
						<td><?= htmlspecialchars($formedGender, ENT_QUOTES, 'UTF-8') ?></td>
					</tr>
					<tr>
						<th scope="row">メールアドレス</th>
						<td><?= htmlspecialchars($email, ENT_QUOTES, 'UTF-8') ?></td>
					</tr>
					<tr>
						<th scope="row">電話番号</th>
						<td><?= htmlspecialchars($tel, ENT_QUOTES, 'UTF-8') ?></td>
					</tr>
					<tr>
						<th scope="row">パスワード</th>
						<td><?= htmlspecialchars($password, ENT_QUOTES, 'UTF-8') ?></td>
					</tr>
				</tbody>
			</table>
      <input type="hidden" name="name" value="<?= $name ?>"> 
      <input type="hidden" name="birthday" value="<?= $birthday ?>"> 
      <input type="hidden" name="gender" value="<?= $gender ?>"> 
      <input type="hidden" name="email" value="<?= $email ?>"> 
      <input type="hidden" name="tel" value="<?= $tel ?>"> 
      <input type="hidden" name="password" value="<?= $password ?>"> 
    <?= $this->tag->submitButton("登録") ?>
		<input type="button" onclick="history.back()" value="戻る">

    </form>
</div>
<?php endif; ?> 
