<div class="text-center m-5"><?= $this->flashSession->output() ?></div>
<div class="text-center border m-5 p-3">
    <?php echo $this->tag->form("customer/checkLogin"); ?>
    <h1>ログイン</h1>
    <p>会員のログインID/パスワードでログインしてください。</p>
    <p>
        <label>メールアドレス</label>
        <?= $this->tag->textField(array('email', 'value' => $email)); ?>
    </p>
    
    <p>
        <label>パスワード</label>
        <?= $this->tag->passwordField(array('password', 'value' => $password)); ?>
    </p>

        <div class="mt-3">
        <button class="btn btn-warning">ログインする</button>
        </div>
    </form>
</div>
