<div class="text-center m-5"><?= $this->flashSession->output() ?></div>

<div class="text-center border m-5 p-3">
    <h1>新規会員登録</h1>
    <?= $this->tag->form("customer/checkSignup") ?>
    <dl>
        <dt>氏名</dt>
        <dd>
            <?= $this->tag->textField(array('name', 'value' => $name)) ?>
        </dd>
        
        <dt>生年月日</dt>
        <dd>
        <?= $this->tag->dateField(array('birthday', 'value' => $birthday, 'min' => '1950-01-01')) ?>
        </dd>
    
        <dt>性別</dt>
        <dd>
            <?php $options = array('' => '----','1' => '男性', '2' => '女性') ?>
            <?= $this->tag->selectStatic(array('gender', 'value' => $gender, $options)) ?>
        </dd>
        
        <dt>メールアドレス</dt>
        <dd>
            <?= $this->tag->emailField(array('email', 'value' => $email)) ?>
        </dd>
        
        <dt>電話番号</dt>
        <dd>
            <!-- <?= $this->tag->numericField("tel") ?> -->
            <?= $this->tag->numericField(array('tel', 'value' => $tel)) ?>
        </dd>
        
        <dt>パスワード</dt>
        <dt>(半角英数)</dt>
        <dd>
            <?= $this->tag->passwordField(array('password', 'value' => $password, 'placeholder' => '※6文字以上32文字以下')) ?> 
        </dd>
        <dt>パスワード(確認用)</dt>
        <dd>
            <?= $this->tag->passwordField(array('confirm', 'value' => $confirm, 'placeholder' => '※6文字以上32文字以下')) ?> 
        </dd>
    </dl>
    <?= $this->tag->submitButton("確認ページへ") ?>
    <input type="button" onclick="history.back()" value="戻る">
    </form>
</div>
