<div class="text-left mb-5">
    <h1>予約内容確認</h1>
</div>
    
<div class="m-auto w-50 border">
  <div class="text-center">
    <h2>予約内容</h2>
      <table class="table">
        <tbody>
					<tr>
						<th scope="row">ホテル名</th>
						<td><?= $room->hotelName ?></td>
					</tr>
					<tr>
						<th scope="row">部屋タイプ</th>
						<td><?= $room->room_type ?></td>
					</tr>
					<tr>
						<th scope="row">チェックイン日</th>
						<td><?= date('Y年m月d日', strtotime($checkInDate)) ?></td>
					</tr>
					<tr>
						<th scope="row">チェックアウト日</th>
						<td><?= date('Y年m月d日', strtotime($checkOutDate)) ?></td>
					</tr>
					<tr>
						<th scope="row">人数</th>
						<td><?= $personCount ?>名</td>
					</tr>
					<tr>
						<th scope="row">合計金額</th>
						<td><?= number_format($room->price) ?>円</td>
					</tr>
				</tbody>
			</table>
	</div>

	<div class="text-center">
		<h2>お客様情報</h2>
			<table class="table">
				<tbody>
					<tr>
						<th scope="row">氏名</th>
						<td><?= htmlspecialchars($name, ENT_QUOTES, 'UTF-8') ?></td>
					</tr>
					<tr>
						<th scope="row">生年月日</th>
						<td><?= date('Y年m月d日', strtotime($birthday)) ?></td>
					</tr>
					<tr>
						<th scope="row">性別</th>
						<td><?= $formedGender ?></td>
					</tr>
					<tr>
						<th scope="row">メールアドレス</th>
						<td><?= htmlspecialchars($email, ENT_QUOTES, 'UTF-8') ?></td>
					</tr>
					<tr>
						<th scope="row">電話番号</th>
						<td><?= htmlspecialchars($tel, ENT_QUOTES, 'UTF-8') ?></td>
					</tr>
				</tbody>
			</table>
	</div>
</div>
<div class="text-center">
<?php echo $this->tag->form("reservation/complete"); ?>
	<input type="hidden" name="roomId" value="<?= $roomId ?>">
	<input type="hidden" name="checkInDate" value="<?= $checkInDate ?>">
	<input type="hidden" name="checkOutDate" value="<?= $checkOutDate ?>">
	<input type="hidden" name="personCount" value="<?= $personCount ?>">
	<input type="hidden" name="price" value="<?= $room->price ?>">
	<input type="hidden" name="priceId" value="<?= $room->priceId ?>">
	<input type="hidden" name="name" value="<?= $name ?>">
	<input type="hidden" name="gender" value="<?= $gender ?>">
	<input type="hidden" name="birthday" value="<?= $birthday ?>">
	<input type="hidden" name="email" value="<?= $email ?>">
	<input type="hidden" name="tel" value="<?= $tel ?>">
	<input type="hidden" name="userId" value="<?= $_SESSION['id'] ?>">
	<button type="submit" class="btn btn-primary mt-1">予約を完了する</button>
</form>
</div>

<div class="text-center mt-5">
	<input type="button" onclick="history.back()" value="戻る">
</div>